kind: Deployment
apiVersion: apps/v1
metadata:
  name: restaurant
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant
      scope: demo
  template:
    metadata:
      labels:
        app: restaurant
        scope: demo
    spec:
      containers:
        - name: restaurant-demo-app
          image: "robipozzi/rpozzi-restaurants:1.0"
---
kind: Service
apiVersion: v1
metadata:
  name: restaurant-service
  namespace: default
spec:
  selector:
    app: restaurant
    scope: demo
  type: NodePort
  ports:
    - protocol: "TCP"
      port: 8082
      nodePort: 31112
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: restaurant-ingress
  namespace: default
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /restaurant
        backend:
          serviceName: restaurant-service
          servicePort: 8082