kind: PersistentVolume
apiVersion: v1
metadata:
  name: restaurant-nfs-pv
  namespace: default
spec:
  storageClassName: nfs
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 10.0.10.3
    path: "/var/nfsshare"