kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: upload-dir-pvc
  namespace: default
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi