kind: Secret
apiVersion: v1
metadata:
  name: mysql-secret-config
type: Opaque
data:
  mysql_dbname: a2Nj
  mysql_username: YWRtaW4=
  mysql_password: mvUQfsIu4mXCoTXP9ewQQ0PTkgGqv3MYcsp4g2SKS5E=
  mysql_root_password: WKJzRztxLn9/EhKKGXAeX5u53vP3pJQUYsrUOofuli4=